export default {
  login: "VeladzicS",
  id: 73850922,
  node_id: "MDQ6VXNlcjczODUwOTIy",
  avatar_url: "https://avatars.githubusercontent.com/u/73850922?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/VeladzicS",
  html_url: "https://github.com/VeladzicS",
  followers_url: "https://api.github.com/users/VeladzicS/followers",
  following_url:
    "https://api.github.com/users/VeladzicS/following{/other_user}",
  gists_url: "https://api.github.com/users/VeladzicS/gists{/gist_id}",
  starred_url: "https://api.github.com/users/VeladzicS/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/VeladzicS/subscriptions",
  organizations_url: "https://api.github.com/users/VeladzicS/orgs",
  repos_url: "https://api.github.com/users/VeladzicS/repos",
  events_url: "https://api.github.com/users/VeladzicS/events{/privacy}",
  received_events_url: "https://api.github.com/users/VeladzicS/received_events",
  type: "User",
  site_admin: false,
  name: "Veladzic S",
  company: null,
  blog: "www.skymediadev.com",
  location: null,
  email: null,
  hireable: null,
  bio: "JavaScript Developer that specializes in React.",
  twitter_username: null,
  public_repos: 8,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-11-02T19:02:59Z",
  updated_at: "2021-01-12T07:16:57Z",
};
